# version: '3.9'


# Set up networks
networks:
  react-net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.99.0/24
          gateway: 172.20.99.1
    internal: false
  
  data-net:
    driver: bridge
    ipam:
      driver: default
      config: 
        - subnet: 172.20.100.0/24
          gateway: 172.20.100.1
    internal: true 
  

# Set up services
services:
  front:
    container_name: "front-cuci-sepatu"   
    build: 
      context: .                
      dockerfile: ./Docker/Dockerfile.node            
    restart: always              
    volumes:
      - .:/app                     
      - /app/node_modules
    depends_on:
      - data_base
    networks:
      - react-net   
      - data-net



  data_base:
    container_name: "data_cuci-sepatu"
    build:
      context: .
      dockerfile: ./Docker/Dockerfile.mysql
    volumes:
      - .:/scripts
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    env_file:
      - ./env/mysql.env
    networks:
      - data-net

  nginx:
    container_name: "nginx-cuci-sepatu"
    build:
      context: .
      dockerfile: ./Docker/nginx.Dockerfile
    ports:
      - "8080:80"
    restart: always
    depends_on:
      - front
    networks:
      - react-net