FROM mysql:8.0 AS build

#set wrorking directory
WORKDIR /scripts

COPY  ./sql /docker-entrypoint-initdb.d ./

# Stage 2: Final image
FROM mysql:8.0

# Copy initialization scripts from builder stage
COPY --from=build /docker-entrypoint-initdb.d /docker-entrypoint-initdb.d

# Expose MySQL port
EXPOSE 3306